name: Carbon
main: com.lastabyss.carbon.Carbon
description: Adds 1.8 blocks and features to the Spigot protocol hack.
softdepend: [ProtocolLib]
startup: STARTUP
version: 1.6
authors: [Navid K., Shevchik, Aust1n46]
