name: Carbon
main: com.lastabyss.carbon.Carbon
description: Adds 1.8 blocks and features to the Spigot protocol hack.
softdepend: [ProtocolLib]
startup: STARTUP
version: 1.6.4
authors: [Navid K., _Shevchik_, Aust1n46]

commands:
  carbon:
    description: Carbon mod command.
    usage: /<command> [argument]