/*
 * Copyright (c) 2004, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package sun.jvmstat.perfdata.monitor;

/**
 * Class for encapsulating syntax exceptions generated by AliasFileParser.
 *
 * @author Brian Doherty
 * @since 1.5
 */
@SuppressWarnings("serial")
public class SyntaxException extends Exception {
	int lineno;

	public SyntaxException(int lineno) {
		this.lineno = lineno;
	}

	public String getMessage() {
		return "syntax error at line " + lineno;
	}
}
